### ISSUE TITLE
Call to `enable_result_type_inference` is not safe

### ISSUE THREAD

**Issue by Danacus** [raviqqe/melior#275]
Calling `enable_result_type_inference` on `OperationBuilder` may trigger undefined behavior if types cannot be inferred, since `mlirOperationCreate` returns a `nullptr` in this case. `OperationBuilder::build` does not check for nullity, and as such an invalid `Operation` may be constructed, causing undefined behavior when it is accessed or dropped.

Code to reproduce:

```rust
{
    let _ = OperationBuilder::new("test", location)
        .enable_result_type_inference()
        .build();
}
```

Suggested fix: check for nullity before calling `Operation::from_raw` in `OperationBuilder::build` and return a `Result<Operation, _>` or simply panic.

**Comment by raviqqe** [comment]
Thanks for the research!

**Comment by raviqqe** [comment]
Sorry, I closed by mistake!
