### ISSUE TITLE
Upcoming LLVM 18

### ISSUE THREAD

**Issue by edg-l** [raviqqe/melior#405]
Jan 23: release/18.x branch created
    Jan 26: 18.1.0-rc1
    Feb 6: 18.1.0-rc2
    Feb 20: 18.1.0-rc3
    Mar 5: 18.1.0
    Mar 19: 18.1.1
    Apr 2: 18.1.2
    Apr 16: 18.1.3
    Apr 30: 18.1.4
    May 14: 18.1.5
    May 28: 18.1.6 (If necessary)

https://discourse.llvm.org/t/llvm-18-release-schedule/76175

LLVM 18 looks like it will release soon.

Some new things it will have are the `mlirTranslateToLLVMIR` (which needs a llvm_sys context btw).

I'm also planning to land a pr soon adding all the LLVM DINode debug attributes, so debug info actually shows up on the generated llvm ir, hoping it will land in 18 too: https://github.com/llvm/llvm-project/compare/main...edg-l:llvm-project:mlir_c_llvm_attributes

Making this issue more as an informative thing.

**Comment by Tiggilyboo** [comment]
I'm experimenting with LLVM 18 on my fork: https://github.com/Tiggilyboo/melior/tree/llvm18

There were a few changes to accessible APIs and some new, I'm sure I missed a few. Sadly it takes quite a few forks to get this rolling, with mlir-sys, tblgen-rs, and the macro crate all having to be changed - however it does build.

You're welcome to use this as a starting point for experiments. Good luck

**Comment by raviqqe** [comment]
@Tiggilyboo Thank you for the work!

**Comment by edg-l** [comment]
llvm 18 seems to be ready in the ecosystem for melior to use it

**Comment by edg-l** [comment]
Done in #530
